project_id = "efhsckzltglpygmwezhj"

[functions.portal-verify]
verify_jwt = false

[functions.portal-session-status]
verify_jwt = false

[functions.portal-data]
verify_jwt = false

[functions.file-gateway]
verify_jwt = false
