
-- Tighten the double-advance guard: only skip when the paid invoice
-- is the exact same invoice_id currently linked to the renewal AND
-- last_generated_billing_date is set (meaning it was auto-generated).
CREATE OR REPLACE FUNCTION public.advance_renewal_on_invoice_paid()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
AS $$
DECLARE
  _renewal RECORD;
  _new_date DATE;
  _actor_id UUID;
  _actor_name TEXT;
BEGIN
  IF OLD.status = 'paid' OR NEW.status != 'paid' THEN
    RETURN NEW;
  END IF;

  FOR _renewal IN
    SELECT id, next_billing_date, interval_months, workspace_id,
           last_generated_billing_date, invoice_id
    FROM public.renewals
    WHERE invoice_id = NEW.id
      AND is_active = true
  LOOP
    -- PRECISE GUARD: skip advance only when this exact invoice was
    -- auto-generated by the renewal system (last_generated_billing_date set
    -- AND invoice_id matches the paid invoice). The generation RPC already
    -- advanced next_billing_date, so advancing again would double-advance.
    IF _renewal.last_generated_billing_date IS NOT NULL
       AND _renewal.invoice_id = NEW.id THEN
      CONTINUE;
    END IF;

    -- Legacy path: manually linked invoice → advance on payment
    _new_date := _renewal.next_billing_date + (_renewal.interval_months || ' months')::interval;

    UPDATE public.renewals
    SET next_billing_date = _new_date,
        updated_at = now()
    WHERE id = _renewal.id;

    _actor_id := auth.uid();
    IF _actor_id IS NOT NULL THEN
      SELECT full_name INTO _actor_name FROM public.profiles WHERE user_id = _actor_id LIMIT 1;
    END IF;

    INSERT INTO public.audit_logs (workspace_id, actor_id, actor_name, action, entity_type, entity_id, metadata)
    VALUES (
      _renewal.workspace_id,
      _actor_id,
      _actor_name,
      'renewal_auto_advanced',
      'renewal',
      _renewal.id,
      jsonb_build_object(
        'invoice_id', NEW.id,
        'invoice_number', NEW.invoice_number,
        'previous_billing_date', _renewal.next_billing_date,
        'new_billing_date', _new_date,
        'interval_months', _renewal.interval_months
      )
    );
  END LOOP;

  RETURN NEW;
END;
$$;
